services:
  homematic-bridge:
    build: .
    container_name: homematic-bridge
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Vienna
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - ./config/internal_config.yaml:/app/config/internal_config.yaml
      - ./data:/app/data
      - ./logs:/app/logs
